build:
  version: "1.0"
  javaVersion: "21"
cards:
  message: "Welcome to cards related prod API's"
  contactDetails:
    name: "Sanskar Singhal - prod"
    email: "pinchusinghal6@gmail.com"
  OnCallSupport:
    -(91)9999999999