build:
  version: "3.0"
  javaVersion: "21"
loans:
  message: "Welcome to loans related local API's"
  contactDetails:
    name: "Sanskar Singhal"
    email: "pinchusinghal6@gmail.com"
  OnCallSupport:
    -(91)9999999999