build:
  version: "2.0"
  javaVersion: "21"
accounts:
  message: "Welcome to accounts related QA API's"
  contactDetails:
    name: "Sanskar Singhal - QA"
    email: "pinchusinghal6@gmail.com"
  OnCallSupport:
    -(91)9999999999