build:
  version: "3.0"
  javaVersion: "21"
accounts:
  message: "Welcome to accounts related local API's"
  contactDetails:
    name: "Sanskar Singhal"
    email: "{cipher}fb1e995ecf2059aa78c965e6f19b30abdb64bf29d2db86eb66eddebc2609236f337c2188c801961f8c0fc59cffee6fad"
  OnCallSupport:
    -(91)9999999999