build:
  version: "1.0"
  javaVersion: "21"
accounts:
  message: "Welcome to accounts related prod API's"
  contactDetails:
    name: "Sanskar Singhal - prod"
    email: "pinchusinghal6@gmail.com"
  OnCallSupport:
    -(91)9999999999